### PR TITLE
static banner upgrade form

### PR DESCRIPTION
**Pull request by WMDE-Fisch**
added 2nd from step for SEPA
added basic interaction and sliding
some cleanup and renaming

### CODE REVIEW

**Comment by wmde-manicki** [comment]
Had a look and looks good (although haven't checked the layout with the ruler).
I have noticed two things. Might be that these are just not done yet and therefore left out on purpose:
 - Closing of the SEPA confirmation (with the Schliessen at the bottom) does not work. The first-step form closes like a charm
 - When choosing periodic donation, the list of possible interval does not slide down but simply shows up

**Comment by wmde-manicki** [comment]
Had a look in Firefox, some remarks:
 - banner expands down a bit after choosing recurring donation (when the intervals pop up). It has not been included in the mock up if I am not mistaken. I find it a bit awkward. But on the other hand there is not spare place to put the intervals in. Maybe in that case only the form part should expand down? Should will call Mr. Artist?
 - Mentioned it already when looking at the earlier version, and still don't know if this remark should be considered at all. But: when choosing the recurring donation, interval radio buttons do not slide down but just appear. Again, how it should look like has not been mentioned in the mock up.
 - Not sure whether it'd be intended but I kind of expected that when I click at the same payment method's button for the second time it'd roll the form up (hide it). It does not happen, form could only be closed be clicking the "Schliessen". I goes it might not actually be intended, and might not be that straightforward feature to add.

Apart of those minor remarks (which might actually not even be something that needs to be changed/fixed) looks really good. "Lightboxes" looked good, including the other layout of those in the narrower browser window.

**Comment by WMDE-Fisch** [comment]
answering from top to bottom:
- yeah I dont know how to do that nicer might ask Mr. UX
- in the "original" banners there also was no sliding effect, will ask Mr. UX
- also already thought of that - I will include it in the next version

**Comment by wmde-manicki** [comment]
Closing form after clicking the payment method button again looks good and works as I'd expect it, nice! Also take a look in Chromium and looks good as well. Good job!
So @WMDE-Fisch are done with changes in this pull request or is there still something coming up?
Sliding of recurring donation intervals could be also added separately, I guess? Or are you going to add it here as well?

**Comment by WMDE-Fisch** [comment]
@wmde-manicki no changes planed atm. They should be part of an other PR. ( this is big enough )

**Comment by wmde-manicki** [comment]
Right, great!

**Pull request merged**
