### PR TITLE
added general padding to input fields and adjusted sizes

### PR DESCRIPTION
**Pull request by WMDE-Fisch**

### CODE REVIEW

**Comment by WMDE-Fisch** [comment]
fixes https://github.com/wmde/fundraising/issues/745

**Comment by wmde-manicki** [comment]
this also makes fields bigger in terms of height. Didn't we only wanted to add padding/margin on the left and right side of the field?

**Comment by WMDE-Fisch** [comment]
I liked the fields being a bit higher so the text also is not glued on the top and bottom - opinions?

**Comment by wmde-manicki** [comment]
I have asked @snaterlicious about this. He said that the original idea of having no padding was due to the fact that adding a padding to text fields would probably be also reflected in the custom amount field. Adding padding on top and bottom would affect the height of the custom amount field (I've just checked that change here actually does it), and this is not what was intended - it should be same as in the "old" form.
That said he suggested adding padding only on the left and right. Thank you for this analysis @snaterlicious !

**Comment by WMDE-Fisch** [comment]
kk fixed - thanks for asking @wmde-manicki

**Pull request merged**
