### PR TITLE
Fix spacing and alignment

### PR DESCRIPTION
**Pull request by gbirke**
The "250 €" was breaking in IE so i had to reduce the padding a bit.
I reduced the padding on the right side, having to add it back on the
last element.

Also aligned the radio buttons for the period.

This fixes https://github.com/wmde/fundraising/issues/795

### CODE REVIEW

**Comment by wmde-manicki** [comment]
Question before I start testing this: Looking at a diff it seems like this is reverting changes done in https://github.com/wmde/FundraisingBanners/pull/54, and then adding some things related to padding etc (as you are saying in the description).
Is the reverting of font-related stuff intended here?

**Comment by gbirke** [comment]
The revert is by accident, I only wanted to change some padding.

**Comment by gbirke** [comment]
Ok, nowI've reverted and force-pushed and it's like I intended, please review.

**Comment by wmde-manicki** [comment]
+1 right now as I checked it on FF/Ubuntu and looked fine.
Will be +2 when I manage to see it also works on IE

**Comment by wmde-manicki** [comment]
Checked again in IE8-11 and looks good, so +2

**Pull request merged**
