### PR TITLE
Banner template validation

### PR DESCRIPTION
**Pull request by gbirke**
Validate the form data on the server side.
Check bank data if "Lastschrift" is selected.
Validate SEPA confirmation step.

### CODE REVIEW

**Comment by WMDE-Fisch** [comment]
generally looks good - apart from the comment about bank data
when merging the SEPA confirmation stuff we might refactor the getAmount stuff

**Comment by wmde-manicki** [comment]
@WMDE-Fisch I have just entered the IBAN and BIC that you mentioned in the comment, and I have not been blocked by form. Which is, I believe, exactly how it is processed in the "old" donation form, and also how it is expected to happen. But I got blocked by form requiring me to enter BLZ and old-style account number if the country was Germany. Switching to e.g. Belgium helps.
That's the way how server-side validation works. It only requires extra bank data if country is DE. I thought it makes sense. Alternative would be to make this decision not looking what it the country but checking the first two characters of IBAN.
I am not sure which way is better. I could change the server-side validation if preferred.

**Comment by wmde-manicki** [comment]
New things added here look fine for me!
The major problem is that donation site seems not to be able to process data from the banner when donating using BEZ. At least I got empty page on my local instance instead of confirmation page. But this should be done in the fundraising's "frontend". Data is stored properly in the database, so banner's part seems OK!

Looking at the code I'd possibly see some little style issues related to spacing but as there are still no automated CS checks this might not be that urgent. Generally code changes look good!

Few remarks:
 - has this been like this before that whatever is the result of validation of field value, the field always gets the "green tick" icon after its validation is done? It seems odd to me to have a field with green tick and the error box saying "Please correct this" at the same time
 - probably to be discussed with the Designer but: Once entered some invalid data, I'd expect error box for particular field disappear when I have entered/I am entering something new to the field. When I have some error boxes, I found discouraging that I am fixing the data but boxes are still there until I click submit again :) Even if this remark is relevant (I don't know what it is intended to be), I'd consider it as not required to be done as a part of this PR.

**Comment by wmde-manicki** [comment]
After merging https://github.com/wmde/FundraisingBanners/pull/20 this now needs a rebase (different versions of `getAmount` function). Sorrey!

**Comment by gbirke** [comment]
Ok, rebased to master and addressed the icon issue. I think now this can be merged.

**Comment by wmde-manicki** [comment]
No icons in the fields at all now. But this is a topic for another pull request :)
Good work!

**Pull request merged**
